### ISSUE TITLE
Help with recreate the Antarctic banner.

### ISSUE THREAD

**Issue by pwongpan** [dengwirda/jigsaw-geo-tutorial#3]
Hi Darren,
I really like your JIGSAW software. I finally can install the JIGSAW-matlab on my computer.
I was wondering how to create the figure like your banner that I attached with JIGSAW?
How did you render the 3D Antarctic continent? Did you use one of the examples included in the tutorial.
Thanks in advance for your help, Pat

**Comment by pwongpan** [comment]
> Hi Darren,
> I really like your JIGSAW software. I finally can install the JIGSAW-matlab on my computer.
> I was wondering how to create the figure like your banner that I attached with JIGSAW?
> How did you render the 3D Antarctic continent? Did you use one of the examples included in the tutorial.
> Thanks in advance for your help, Pat

This banner I mean. Thanks again.
![banner](https://user-images.githubusercontent.com/69950454/94224346-67ea9d80-ff35-11ea-916d-9a7b225fa490.jpg)

**Comment by dengwirda** [comment]
Hi Pat,
The mesh in the banner was made more for the image than as an actual climate config., but it is indeed possible to set something like this up in `jigsaw` for `MPAS-O|[SI|LI]`. 

The tutorial / example code will hopefully point you in the right direction here --- essentially you need to define a "spacing" function (in lon-lat coord.'s) that describes the variation in cell edge-length that you desire. Once you have this, `jigsaw` will build a mesh that satisfies those constraints, while trying to keep the cells "nicely" shaped.

I rendered the banner image direct in `MATLAB`, but `Paraview` is possibly easier to work with.

**Comment by pwongpan** [comment]
Thanks Darren. Can JIGSAW create Voronoi mesh like the banner or MPAS mesh instead of the Delaunay triangular mesh in the example?

**Comment by dengwirda** [comment]
Hi Pat,
Yes, Delaunay and Voronoi meshes are [the "duals" of each other](https://scicomp.stackexchange.com/questions/771/how-are-the-voronoi-tesselation-and-delaunay-triangulation-problems-duals-of-eac), so `jigsaw` can be used to generate grids for `MPAS` --- generally, it's the standard package used for ocean, sea-ice, land-ice, meshes, etc.

Are you an `MPAS` user / developer? If so, there's a range of tools [here](https://github.com/MPAS-Dev/MPAS-Tools) that may be helpful in setting up `MPAS`-format mesh files. The process typically involves building the triangulation using `jigsaw`, and then assembling the Voronoi mesh + data-structures using `MPAS-Tools`...

What are you looking to set up?

**Comment by pwongpan** [comment]
Thanks a lot Darren. I am just studying and try to understand how the MPAS mesh was generated which is really cool. Thanks again.
