### ISSUE TITLE
Mesh tool and data interpolation

### ISSUE THREAD

**Issue by dinghao1995** [dengwirda/jigsaw-geo-tutorial#4]
Hi,
I'm a new user here and I want ask some questions to you. Now, I'm using MPAS-Ocean model and do some studies, and so I'm using the JIGSAW tool to create the "mesh" for the model. Now, I'm using your "jigsaw-geo-tutorial" code and create the "mesh.msh" file (such as ex_1.m in MATLAB). But I don't how to put the "mesh.msh" file into the model and drive it to run, could you tell me how to do that? Besides, I have ERA5 data (u10, v10) and SODA data (such as TEMP, SALT), so I want use those data to drive the MPAS-Ocean model, how can I interpolate the ERA5 or SODA data into the "mesh.msh" file?
Thanks.

**Comment by dengwirda** [comment]
Hi @dinghao1995, while it's fairly easy to create new meshes for MPAS/E3SM using jigsaw it's typically a fair bit more involved to create full E3SM configurations. Are you working with the E3SM team on a specific project? If not, perhaps starting from one of the standard E3SM config.'s could be an option: https://e3sm.org/model/running-e3sm/e3sm-quick-start/
I'll close this issue for now, as the E3SM init. + spin-up process is handled outside of jigsaw.
